### ISSUE TITLE
Libcr problem

### ISSUE THREAD

**Issue by iunderstand** [swiseman/nn_coref#1]
I run the python script, but get the error:
luarocks/loader.lua:154: Invalid data in manifest file for module libcr (invalid data for cr scm-1)
stack traceback:
    [C]: in function 'error'
    .../torch/install/share/lua/5.2/trepl/init.lua:384: in function 'require'
    init.lua:3: in main chunk
    [C]: in function 'dofile'
    full_g1_model.lua:2: in main chunk
    [C]: in function 'dofile'
    .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: in ?
I cd to the "nn" folder and compile: "luarocks make cr-scm-1.rockspec" and then re-run, but the problem still remains..
Anybody know the issue?

**Comment by swiseman** [comment]
I assume you have 'nn' installed?

**Comment by iunderstand** [comment]
i have installed the nn package...

**Comment by swiseman** [comment]
Hmm, I'm not sure what the issue is; there isn't a lot to go on in that error message, unfortunately. I recently pushed a simplified version of the ACL model (nn/vanilla_mr.lua), though, which doesn't require anything to be compiled, so that might be a good option.

**Comment by iunderstand** [comment]
got it, thanks.
