### ISSUE TITLE
Hdf5 issue

### ISSUE THREAD

**Issue by thanakorntr** [swiseman/nn_coref#2]
Hi Sam,

I've encountered an issue I believe related to hdf5 when running the vanilla_mr.lua. I have installed all necessary packages (nn, hdf5), and have put all resources in their right location (hdf5 files and other required data). When running th vanilla_mr.lua, the following error appears: 

$ th vanilla_mr.lua -PT
/Users/Thanakorn/torch/install/bin/lua: /Users/Thanakorn/torch/install/share/lua/5.2/hdf5/group.lua:312: HDF5Group:read() - no such child 'feats' for [HDF5Group 33554432 /]
stack traceback:
    [C]: in function 'error'
    /Users/Thanakorn/torch/install/share/lua/5.2/hdf5/group.lua:312: in function </Users/Thanakorn/torch/install/share/lua/5.2/hdf5/group.lua:302>
    (...tail calls...)
    ./sparse_doc_data.lua:10: in function 'loadFromH5'
    vanilla_mr.lua:307: in function 'main'
    vanilla_mr.lua:349: in main chunk
    [C]: in function 'dofile'
    ...korn/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: in ?

Any suggestions would be appreciated! Thanks!

**Comment by swiseman** [comment]
Hmm, it looks like hdf5 isn't finding the pairwise feature files. I just reconfirmed that the script works for me, so as a sanity check, can you check that you've done all of the following:
1) Download both *-feats.h5.bz2 and *-offsets.h5.bz2 from the link in the README
2) bunzip2 all the bzipped files
3) If you don't supply a different path for the hdf5 features, make sure you are running the script from the same directory as the hdf5 files, and that you haven't changed their names. (For instance, after unzipping,  the train hdf5 files should be called train_small-pw-feats.h5 and train_small-pw-offsets.h5, which is what the default arguments in vanilla_mr.lua expect).

**Comment by thanakorntr** [comment]
Hi Sam, you were right! I've downloaded the h5 files and I was able to train the model now. Thanks again!
