### ISSUE TITLE
Extract features for gold mentions

### ISSUE THREAD

**Issue by fabbyd** [swiseman/nn_coref#5]
Hi Sam,

Let me first thank you. Your implementation helped me understand a lot of stuff with coreference, Torch and neural networks.

I am trying to use your version of the Berkeley feature extractor under modifiedBCS but I am having trouble using it for gold mentions. I used it on automatic mentions already without problems.

Here is what I tried:

    java -jar -Xmx30g modifiedBCS/target/scala-2.11/moarcoref-assembly-1.jar ++modifiedBCS/base.conf -execDir execdir -numberGenderData modifiedBCS/gender.data -animacyPath modifiedBCS/animate.unigrams.txt -inanimacyPath modifiedBCS/inanimate.unigrams.txt -trainPath ./data/flat_gold_conll_train_2012/ -devPath ./data/flat_gold_conll_dev_2012/ -testPath ./data/flat_test_2012/ -mode SMALLER -conjType NONE -pairwiseFeats FINAL+MOARANAPH+MOARPW -trainOnGold
    main() {
      Execution directory: execdir
      Using conjType = NONE
      Reading Bergsma and Lin file from modifiedBCS/gender.data
      Done!
      ERROR: java.lang.IllegalArgumentException: requirement failed:
    scala.Predef$.require(Predef.scala:207)
    edu.harvard.nlp.moarcoref.FeatureExtractor$.writeSeparatedFeatsAndOraclePredClustering(FeatureExtractor.scala:24)
    edu.harvard.nlp.moarcoref.FeatureExtractor.writeSeparatedFeatsAndOraclePredClustering(FeatureExtractor.scala)
    edu.harvard.nlp.moarcoref.MiniDriver.run(MiniDriver.java:70)
    edu.berkeley.nlp.futile.fig.exec.Execution.runWithObjArray(Execution.java:479)
    edu.berkeley.nlp.futile.fig.exec.Execution.run(Execution.java:432)
    edu.harvard.nlp.moarcoref.MiniDriver.main(MiniDriver.java:64)
      Execution directory: execdir
    1 errors, 0 warnings
    } [3.9s]

The following line seems to be my problem ([FeaturExtractor.scala][1]):

    def writeSeparatedFeatsAndOraclePredClustering(smaller:Boolean) {
        ...
        require(!MiniDriver.trainOnGold);
        ...

Why are you disabling gold mentions? I tried using the options `-trainOnGold`, `-useGoldMentions`, `-docSuffix gold_conll` to no avail.

   [1]: https://github.com/swiseman/nn_coref/blob/master/modifiedBCS/src/main/java/edu/harvard/nlp/moarcoref/FeatureExtractor.scala#L24

**Comment by swiseman** [comment]
Hi,

Sure! Hmm, I think the reason I disabled using gold mentions was partially for sanity, and also because it's less necessary to extract anaphoricity features when you're using gold mentions. Have you tried recompiling w/o that require statement in FeatureExtractor.scala? Do things break?

**Comment by fabbyd** [comment]
I just recompiled w/o that line and everything seems to be running fine. If this line was only for sanity, then I shall be insane.

Thank you for your answer!

**Comment by fabbyd** [comment]
**EDIT 3:** Alright. Decided to get my hands dirty and finally found out that it was not possible. I did a [PR][1] to "fix" that. Like I suspected, even though I removed the require, the system was still not loading the gold mentions but was predicting them instead. After this fix I finally get a recall of 100%.

Sorry for laying out my thought process on you here hehe.

-------

Also, what is the difference between the options `-trainOnGold`, `-useGoldMentions`, `-docSuffix gold_conll`? I read the code a bit, but I mostly use it as a black box tbh. All I want is to extract features for gold mentions so that I can train a coreference system on them (i.e. train without singletons).

I'm asking this because after running the program with `-trainOnGold` (which ran perfectly fine w/o the require btw) it eventually prints the following:

```
Detected 378796 predicted mentons (197132 nominal, 96950 proper, 79055 pronominal), 154162 / 155559 = 0.9910194845685559 gold mentions recalled (104 missed ones are not constituents)
```
(notice the typo on 'mentons' ^^^) 
Shouldn't it be 100% recall? Or is it actually reextracting the mentions before featurizing them?

**EDIT:** Using `-useGoldMentions` gives the same recall. I guess I could just filter the singletons myself afterwards, but I'ld be surprised if there wasn't already an option for that.

**EDIT 2:** The number of mentions in the feature files produced versus the number of mentions in the raw CoNLL gold files are completely different. I guess this means the program must be reextracting mentions first instead of using the gold mentions. So `-trainOnGold` is not quite what I needed.

   [1]: https://github.com/swiseman/nn_coref/pull/6

**Comment by swiseman** [comment]
Cool, thanks for looking into this! In general, since I only made relatively minor modifications to Greg Durrett's original implementation of the Berkeley Coreference System (here: http://nlp.cs.berkeley.edu/projects/coref.shtml and here: https://github.com/gregdurrett/berkeley-entity) a lot of unnecessary options and things are still floating around the modifiedBCS/ directory. Anyway, I put some comments on the PR.

**Comment by fabbyd** [comment]
#6
